version: '3.8'

services:
  spring-ai-agent:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_AI_OPENAI_API_KEY=${OPENAI_API_KEY}
      - SPRING_AI_VECTORSTORE_PINECONE_API_KEY=${SPRING_AI_VECTORSTORE_PINECONE_API_KEY}
