spring:
  application:
    name: spring-ai-agent
  ai:
    openai:
      api-key: "override-me"
      embedding:
        options:
          model: "text-embedding-3-small"
    vectorstore:
      pinecone:
        index-name: "amplify"
app:
  site:
    baseUrl: "https://amplifyfederal.com"